"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var crypto_1 = require("crypto");
var fs_1 = require("fs");
var nanoid_1 = require("nanoid");
var token = (0, nanoid_1.nanoid)();
var setting = JSON.parse((0, fs_1.readFileSync)(process.cwd() + '/src/private/token.json', { encoding: 'utf8' }));
var hash = (0, crypto_1.createHash)('sha256').update(token).digest('hex');
setting.supportingSchools.edit.push(hash);
(0, fs_1.writeFileSync)(process.cwd() + '/src/private/token.json', JSON.stringify(setting), { encoding: 'utf8' });
console.log('Token: ' + token);
console.log('Hash: ' + hash);
console.log('Please save it down as it will not be shown again');
